version: "3.7"

# 컴퓨터들
services:
  # 컴퓨터이름
  quiz08-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  # 컴퓨터이름
  quiz08-database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
